name: Auto Deploy – Swachify Frontend (DEV)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest DEV code
        run: |
          cd /home/projects/services/SWACHIFY_APPLICATION_INDIA
          git fetch --all
          git checkout dev
          git pull origin dev

      - name: Install dependencies
        run: |
          cd /home/projects/services/SWACHIFY_APPLICATION_INDIA
          npm install

      - name: Build frontend
        run: |
          cd /home/projects/services/SWACHIFY_APPLICATION_INDIA
          npm run build

      - name: Deploy dist to DEV Nginx folder
        run: |
          sudo rm -rf /var/www/swachify-dev/*
          sudo cp -r /home/projects/services/SWACHIFY_APPLICATION_INDIA/dist/* /var/www/swachify-dev/

      - name: Reload Nginx
        run: |
          sudo systemctl reload nginx

